<?php
/**
* Pacific NM (https://www.pacificnm.com)
*
* @link      https://github.com/pacificnm/pnm for the canonical source repository
* @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
* @license
*/
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
					<i class="<?php echo $this->layout()->pageIcon; ?>" aria-hidden="true"></i>
					<?php echo $this->translate($this->layout()->pageTitle); ?> 
					<small><?php echo $this->translate("View"); ?></small>
				</h3>
				<div class="box-tools">
					<?php echo $this->deleteButton("media-delete", array("id" => $this->entity->getMediaId())); ?>
					
					<?php echo $this->updateButton("media-update", array("id" => $this->entity->getMediaId())); ?>
				</div>
			</div>
			<div class="box-body box-profile">
                <h3 class="profile-username text-center"></h3>
                <p class="text-muted text-center"></p>
                <ul class="list-group list-group-unbordered">
                    <li class="list-group-item"></li>
                </ul>
            </div>
		</div>
	</div>
</div>